### PR TITLE
Fixup: typo in CSS variable name

### PR DESCRIPTION
**Pull request by jayaddison**
Noticed while exploring this as an excuse to learn a little about `textual`.

And yes, 5x5 is an annoying puzzle!

### CODE REVIEW

**Comment by jayaddison** [comment]
(also: should the file extension be `.scss`?)

**Comment by davep** [comment]
Thanks for catching that, will properly process when next at my keyboard. To answer the extension question: no, the extension doesn't matter and generally css gets used for Textual css files.

**Comment by davep** [comment]
Now I remember... amusingly about a month ago in the Textual repo (which has a version of this as part of the `examples` directory)... https://github.com/Textualize/textual/commit/daa69d4591466a22419d2864a9355e1461ec4f50

**Comment by jayaddison** [comment]
Thanks - I spotted that after opening, and kinda worried that this pull request was a waste of your time (I also subsequently found and read the Textual CSS docs!).  Anyway - thanks for the merge.

One small question/bugreport in textual itself on the way soon.  Perhaps with a pull request if investigation leads to most-of-the-solution, which it may (unicode, key bindings -- not the character-width issue you [discussed recently](https://github.com/Textualize/textual/issues/1267), though).

**Comment by davep** [comment]
> I spotted that after opening, and kinda worried that this pull request was a waste of your time

Nope, absolutely not. Totally forgot to sort it in this repo when I fixed it over there (this repo started first, then the code got added to Textual as an example, and then I've since taken this code off in a slightly different direction and published it standalone so folk can `pipx install` and play and stuff.

So, yeah, appreciate the PR. :-)

**Pull request merged**
